(() => {
  const $ = (s) => document.querySelector(s), $$ = (s) => [...document.querySelectorAll(s)];
  const repository = "Hamdan852/hamdan-ai", WEBSITE_KEY = "hamdan.websites", params = new URLSearchParams(location.search);
  let selectedProjectId = params.get("project") || "";
  function websites(){try{return JSON.parse(localStorage.getItem(WEBSITE_KEY)||"[]")}catch{return[]}}
  function saveWebsites(x){localStorage.setItem(WEBSITE_KEY,JSON.stringify(x));window.dispatchEvent(new StorageEvent("storage",{key:WEBSITE_KEY}))}
  function selectedProject(){return websites().find(p=>p.id===selectedProjectId)||websites()[0]||null}
  function setSelectedProject(id){selectedProjectId=id||"";const p=selectedProject();if(p)history.replaceState(null,"",`/developer.html?project=${encodeURIComponent(p.id)}`);renderWebsiteProjects();updateExecutionLabel()}
  async function postJson(path,body){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json",accept:"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`${path} failed`);return d}
  async function hamdan(op,body={}){return postJson("/api/hamdan",{op,repository,...body})}
  async function createWebsite(){const input=$("#websiteName"),prompt=$("#developerPrompt"),name=(input?.value||"").trim(),description=(prompt?.value||"").trim();if(!name){input?.focus();return}if(!description){prompt?.focus();return}const result=$("#developerResult");if(result){result.hidden=false;result.innerHTML='<h3>Planning your website…</h3><p>Hamdan Developer is preparing the project structure. No files are being changed yet.</p>'}try{const plan=await postJson("/api/website-create",{repository,name,brief:description,type:"Custom"}),project={...plan.project,status:"Planned",createdAt:new Date().toISOString(),files:plan.files,approvalRequired:plan.approvalRequired};const items=websites().filter(p=>p.id!==project.id);items.unshift(project);saveWebsites(items);setSelectedProject(project.id);if(result)renderWebsitePlan(plan);const notice=$("#websiteCreated");if(notice){notice.hidden=false;notice.textContent=`✓ ${name} planned. Review the plan before generating files.`}}catch(error){if(result){result.hidden=false;result.innerHTML=`<h3>Website planning failed</h3><p>${escapeHtml(error.message)}</p>`}}}
  function renderWebsiteProjects(){const box=$("#websiteProjects");if(!box)return;const items=websites();box.innerHTML=items.length?items.map(p=>`<div class="website-project ${p.id===selectedProjectId?"selected":""}"><div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.status||"Draft")} · ${new Date(p.createdAt).toLocaleDateString()}</small></div><button type="button" data-select-project="${escapeHtml(p.id)}">${p.id===selectedProjectId?"Selected":"Select"}</button></div>`).join(""):'<div class="empty-panel">No websites yet. Create your first website above.</div>';$$("[data-select-project]").forEach(b=>b.addEventListener("click",()=>setSelectedProject(b.dataset.selectProject)));updateExecutionLabel()}
  function updateExecutionLabel(){const p=selectedProject(),box=$("#executionProject");if(box)box.textContent=p?`Selected: ${p.name}`:"No website selected"}
  function renderWebsitePlan(data){const result=$("#developerResult");if(!result)return;result.hidden=false;result.innerHTML=`<h3>Website plan ready</h3><p>${escapeHtml(data.message||"Review this plan before any files are generated.")}</p><div class="workflow-track">${(data.workflow||[]).map((x,i)=>`<span class="workflow-step ${x===data.stage?"current":i<2?"done":""}">${i+1}. ${escapeHtml(x)}</span>`).join("")}</div><div class="plan-priorities"><b>Initial project files</b>${(data.files||[]).map(f=>`<div><strong>${escapeHtml(f.path)}</strong><span>${escapeHtml(f.purpose)}</span></div>`).join("")}</div><div class="inspection-note">Planning only · No code changes · No deployment</div>`}
  $$(".nav").forEach(b=>b.addEventListener("click",()=>{const v=b.dataset.view;$$('.nav').forEach(x=>x.classList.toggle('active',x===b));$$('.view').forEach(x=>x.classList.toggle('active',x.id===v));window.scrollTo({top:0,behavior:'smooth'})}));
  $$(".quick-prompts button").forEach(b=>b.addEventListener("click",()=>{$("#developerPrompt").value=b.dataset.prompt;$("#developerPrompt").focus()}));$("#createWebsite")?.addEventListener("click",createWebsite);$("#websiteName")?.addEventListener("keydown",e=>{if(e.key==="Enter")createWebsite()});
  async function prepareProjectDeployment(p){if(!p)throw new Error("Select a website project first.");const artifact=await hamdan("artifact",{project:{id:p.id,name:p.name},approved:true,files:p.files||[]});return artifact.artifact}
  async function runStage(action,approved=false){const log=$("#executionLog"),status=$("#executionStatus"),p=selectedProject();if(action!=="verify"&&!p){if(status)status.textContent="Select project";if(log)log.textContent="Select a website in My Websites before running this stage.";return}if(status)status.textContent="Checking…";try{let artifact;if(action==="deploy-prepare"){artifact=await prepareProjectDeployment(p);const readiness=await hamdan("vercel-readiness",{projectId:p.id,projectName:p.name,artifactId:artifact.id,environment:"preview"});if(!readiness.configured){if(status)status.textContent="Not configured";if(log)log.innerHTML=`<b>Deployment blocked.</b> ${escapeHtml(readiness.message||"Vercel deployment is not configured.")}<br>Project: ${escapeHtml(p.name)}<br>Artifact: ${escapeHtml(artifact.id)}`;return}}if(status)status.textContent="Running…";const d=await hamdan("run",{action,approved});if(status)status.textContent=d.stage||"Queued";if(log)log.innerHTML=`<b>${escapeHtml(d.action||action)}</b> · ${escapeHtml(d.message||"Accepted")}<br>Project: ${escapeHtml(p?.name||"—")}`;if(action==="deploy-prepare"&&artifact){const deployment=await hamdan("deployment-request",{artifact,target:"preview",approved:true,project:p.name});if(log)log.innerHTML+=`<br>Vercel: ${escapeHtml(deployment.state||"QUEUED")} · ${escapeHtml(deployment.url||deployment.deploymentId||"accepted")}`}}catch(e){if(status)status.textContent="Blocked";if(log)log.textContent=e.message}}
  $("#planRun")?.addEventListener("click",()=>runStage("plan"));$("#generateRun")?.addEventListener("click",()=>runStage("generate",true));$("#testRun")?.addEventListener("click",()=>runStage("test"));$("#deployRun")?.addEventListener("click",()=>{const p=selectedProject();if(!p){$("#executionLog").textContent="Select a website project before deploying.";return}if(confirm(`Authorize deployment of “${p.name}” to preview?`))runStage("deploy-prepare",true)});$("#verifyRun")?.addEventListener("click",()=>runStage("verify"));
  $("#askDeveloper")?.addEventListener("click",async()=>{const prompt=$("#developerPrompt").value.trim();if(!prompt){$("#developerPrompt").focus();return}const result=$("#developerResult");result.hidden=false;result.innerHTML='<h3>Inspecting the project…</h3><p>Hamdan Developer is following its controlled engineering workflow.</p>';try{const assessment=await hamdan("assessment",{prompt}),inspection=await postJson("/api/project-inspect",{repository,ref:"main"}),plan=await postJson("/api/project-plan",{repository,prompt,inspection:{...inspection.summary,files:inspection.files,repository:inspection.repository,readOnly:inspection.scope?.readOnly}});renderResult({...assessment,stage:"Plan",inspection:{repository,readOnly:true},plan})}catch(error){renderResult({title:"Initial engineering assessment",summary:"Inspection was unavailable.",action:`Retry inspection (${error.message})`,risk:"Low — planning only",stage:"Inspect",workflow:["Understand","Inspect","Plan","Approve","Change","Test","Deploy","Verify"]})}});
  function renderResult(data){const result=$("#developerResult"),plan=data.plan,priorities=plan?.plan?.priorities||[];result.innerHTML=`<h3>${escapeHtml(data.title||"Engineering plan")}</h3><p>${escapeHtml(plan?.plan?.objective||data.summary||"No plan generated.")}</p><div class="workflow-track">${(data.workflow||[]).map((x,i)=>`<span class="workflow-step ${x===data.stage?"current":i<(data.workflow||[]).indexOf(data.stage)?"done":""}">${i+1}. ${escapeHtml(x)}</span>`).join("")}</div>${priorities.length?`<div class="plan-priorities"><b>Plan priorities</b>${priorities.map(x=>`<div><strong>${escapeHtml(x.priority)} · ${escapeHtml(x.area)}</strong><span>${escapeHtml(x.reason)}</span></div>`).join("")}</div>`:""}<div class="inspection-note">Read-only inspection · No code changes · No deployment</div>`}
  function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]||c))}renderWebsiteProjects();
})();
