(() => {
  const $ = (s) => document.querySelector(s);
  const $$ = (s) => [...document.querySelectorAll(s)];
  const repository = "Hamdan852/hamdan-ai";
  const WEBSITE_KEY = "hamdan.websites";
  const params = new URLSearchParams(location.search);
  let selectedProjectId = params.get("project") || "";
  function websites(){try{return JSON.parse(localStorage.getItem(WEBSITE_KEY)||"[]");}catch{return[];}}
  function saveWebsites(items){localStorage.setItem(WEBSITE_KEY,JSON.stringify(items));window.dispatchEvent(new StorageEvent("storage",{key:WEBSITE_KEY}));}
  function selectedProject(){return websites().find(p=>p.id===selectedProjectId)||websites()[0]||null;}
  function setSelectedProject(id){selectedProjectId=id||"";const p=selectedProject();if(p)history.replaceState(null,"",`/developer.html?project=${encodeURIComponent(p.id)}`);renderWebsiteProjects();updateExecutionLabel();}
  async function postJson(path,body){const response=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json",accept:"application/json"},body:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`${path} failed`);return data;}
  async function createWebsite(){const input=$("#websiteName"),prompt=$("#developerPrompt"),name=(input?.value||"").trim(),description=(prompt?.value||"").trim();if(!name){input?.focus();return;}if(!description){prompt?.focus();return;}const result=$("#developerResult");if(result){result.hidden=false;result.innerHTML='<h3>Planning your website…</h3><p>Hamdan Developer is preparing the project structure. No files are being changed yet.</p>';}try{const plan=await postJson("/api/website-create",{repository,name,brief:description,type:"Custom"});const project={...plan.project,status:"Planned",createdAt:new Date().toISOString(),files:plan.files,approvalRequired:plan.approvalRequired};const items=websites().filter(p=>p.id!==project.id);items.unshift(project);saveWebsites(items);setSelectedProject(project.id);if(result)renderWebsitePlan(plan);const notice=$("#websiteCreated");if(notice){notice.hidden=false;notice.textContent=`✓ ${name} planned. Review the plan before generating files.`;}}catch(error){if(result){result.hidden=false;result.innerHTML=`<h3>Website planning failed</h3><p>${escapeHtml(error.message)}</p>`;}}}
  function renderWebsiteProjects(){const box=$("#websiteProjects");if(!box)return;const items=websites();box.innerHTML=items.length?items.map(p=>`<div class="website-project ${p.id===selectedProjectId?"selected":""}"><div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.status||"Draft")} · ${new Date(p.createdAt).toLocaleDateString()}</small></div><button type="button" data-select-project="${escapeHtml(p.id)}">${p.id===selectedProjectId?"Selected":"Select"}</button></div>`).join(""):'<div class="empty-panel">No websites yet. Create your first website above.</div>';$$("[data-select-project]").forEach(btn=>btn.addEventListener("click",()=>setSelectedProject(btn.dataset.selectProject)));updateExecutionLabel();}
  function updateExecutionLabel(){const p=selectedProject(),box=$("#executionProject");if(box)box.textContent=p?`Selected: ${p.name}`:"No website selected";}
  function renderWebsitePlan(data){const result=$("#developerResult");if(!result)return;const workflow=(data.workflow||[]).map((item,index)=>`<span class="workflow-step ${item===data.stage?"current":index<2?"done":""}">${index+1}. ${escapeHtml(item)}</span>`).join("");const files=(data.files||[]).map(file=>`<div><strong>${escapeHtml(file.path)}</strong><span>${escapeHtml(file.purpose)}</span></div>`).join("");result.hidden=false;result.innerHTML=`<h3>Website plan ready</h3><p>${escapeHtml(data.message||"Review this plan before any files are generated.")}</p><div class="workflow-track">${workflow}</div><div class="result-grid"><div><b>Project</b><span>${escapeHtml(data.project?.name||"")}</span></div><div><b>Type</b><span>${escapeHtml(data.project?.type||"Custom")}</span></div><div><b>Approval</b><span>Required</span></div><div><b>Writes</b><span>None yet</span></div></div><div class="plan-priorities"><b>Initial project files</b>${files}</div><div class="inspection-note">Planning only · No code changes · No deployment</div>`;}
  $$(".nav").forEach(button=>button.addEventListener("click",()=>{const view=button.dataset.view;$$('.nav').forEach(b=>b.classList.toggle('active',b===button));$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));window.scrollTo({top:0,behavior:'smooth'});}));
  $$(".quick-prompts button").forEach(button=>button.addEventListener("click",()=>{$("#developerPrompt").value=button.dataset.prompt;$("#developerPrompt").focus();}));
  $("#createWebsite")?.addEventListener("click",createWebsite);$("#websiteName")?.addEventListener("keydown",e=>{if(e.key==="Enter")createWebsite();});
  async function deploymentReadiness(p,artifact){return postJson("/api/vercel-deploy-ready",{repository,projectId:p.id,projectName:p.name,artifactId:artifact.id,environment:"preview"});}
  async function prepareProjectDeployment(p){if(!p)throw new Error("Select a website project first.");const manifest=await postJson("/api/deployment-project",{repository,projectId:p.id,projectName:p.name});const artifact=await postJson("/api/deployment-artifact",{repository,projectId:p.id,projectName:p.name,files:p.files||[]});return {manifest,artifact};}
  async function runStage(action,approved=false){const execLog=$("#executionLog"),execStatus=$("#executionStatus"),p=selectedProject();if(action!=="verify"&&!p){if(execStatus)execStatus.textContent="Select project";if(execLog)execLog.textContent="Select a website in My Websites before running this stage.";return;}if(execStatus)execStatus.textContent="Checking…";if(execLog)execLog.textContent=`Checking readiness for ${action}…`;try{let deployment=null;if(action==="deploy"){deployment=await prepareProjectDeployment(p);const readiness=await deploymentReadiness(p,deployment.artifact.artifact);if(!readiness.configured){if(execStatus)execStatus.textContent="Not configured";if(execLog)execLog.innerHTML=`<b>Deployment blocked.</b> ${escapeHtml(readiness.message||"Vercel deployment is not configured.")}<br>Project: ${escapeHtml(p.name)}<br>Artifact: ${escapeHtml(deployment.artifact.artifact.id)}<br>Required server-side configuration: ${escapeHtml((readiness.required||[]).join(", "))}`;return;}if(execLog)execLog.innerHTML=`<b>Deployment ready.</b> Project: ${escapeHtml(p.name)}<br>Artifact: ${escapeHtml(deployment.artifact.artifact.id)}<br>Provider: Vercel · Preview`;}
    if(execStatus)execStatus.textContent="Running…";
    const d=await postJson("/api/execution-worker",{repository,action,approved,requestId:`ui_${action}_${p?.id||"none"}_${Date.now()}`});
    if(execStatus)execStatus.textContent=d.status||"Queued";
    if(execLog)execLog.innerHTML=`<b>${escapeHtml(d.action||action)}</b> · ${escapeHtml(d.message||"Accepted")}<br>Project: ${escapeHtml(p?.name||"—")}<br>Request: ${escapeHtml(d.requestId||"accepted")}<br>Steps: ${(d.steps||[]).map(escapeHtml).join(" → ")}`;
  }catch(e){if(execStatus)execStatus.textContent="Blocked";if(execLog)execLog.textContent=e.message;}}
  $("#planRun")?.addEventListener("click",()=>runStage("build"));$("#generateRun")?.addEventListener("click",()=>runStage("build",true));$("#testRun")?.addEventListener("click",()=>runStage("test"));$("#deployRun")?.addEventListener("click",async()=>{const p=selectedProject();if(!p){const log=$("#executionLog");if(log)log.textContent="Select a website project before deploying.";return;}try{const deployment=await prepareProjectDeployment(p),readiness=await deploymentReadiness(p,deployment.artifact.artifact),log=$("#executionLog"),status=$("#executionStatus");if(!readiness.configured){if(status)status.textContent="Not configured";if(log)log.innerHTML=`<b>Deploy Live is not ready.</b> Project: ${escapeHtml(p.name)}<br>Artifact: ${escapeHtml(deployment.artifact.artifact.id)}<br>${escapeHtml(readiness.message||"Configure Vercel first.")}`;return;}if(confirm(`Authorize deployment preparation for “${p.name}” to production?`))runStage("deploy",true);}catch(e){const log=$("#executionLog");if(log)log.textContent=e.message;}});$("#verifyRun")?.addEventListener("click",()=>runStage("verify"));
  function fallback(prompt){return{title:"Initial engineering assessment",summary:"The request was understood, but live repository inspection was unavailable. No change is proposed without evidence.",action:"Retry inspection before planning or changing code.",risk:"Low — planning only",areas:["Project context","Architecture","Verification"],stage:"Inspect",workflow:["Understand","Inspect","Plan","Approve","Change","Test","Deploy","Verify"],inspection:{repository,readOnly:true}};}
  $("#askDeveloper")?.addEventListener("click",async()=>{const prompt=$("#developerPrompt").value.trim();if(!prompt){$("#developerPrompt").focus();return;}const result=$("#developerResult");result.hidden=false;result.innerHTML='<h3>Inspecting the project…</h3><p>Hamdan Developer is following its controlled engineering workflow.</p>';try{const assessment=await postJson("/api/developer",{prompt});const inspection=await postJson("/api/project-inspect",{repository,ref:"main"});const plan=await postJson("/api/project-plan",{repository,prompt,inspection:{...inspection.summary,files:inspection.files,repository:inspection.repository,readOnly:inspection.scope?.readOnly}});renderResult({...assessment,stage:"Plan",inspection:{repository,readOnly:true},plan});}catch(error){renderResult({...fallback(prompt),action:`${fallback(prompt).action} (${error.message})`});}});
  function renderResult(data){const result=$("#developerResult");const workflow=(data.workflow||[]).map((item,index)=>`<span class="workflow-step ${item===data.stage?"current":index<(data.workflow||[]).indexOf(data.stage)?"done":""}">${index+1}. ${escapeHtml(item)}</span>`).join("");const plan=data.plan;const priorities=plan?.plan?.priorities||[];const evidence=plan?.evidence;result.innerHTML=`<h3>${escapeHtml(data.title||"Engineering plan")}</h3><p>${escapeHtml(plan?.plan?.objective||data.summary||"No plan generated.")}</p><div class="workflow-track">${workflow}</div><div class="result-grid"><div><b>Current stage</b><span>${escapeHtml(data.stage||"Inspect")}</span></div><div><b>Risk level</b><span>${escapeHtml(data.risk||"Planning only")}</span></div><div><b>Repository evidence</b><span>${evidence?`${evidence.inspectedFiles} files inspected · ${evidence.truncated?"truncated":"complete"}`:"Read-only inspection"}</span></div><div><b>Approval</b><span>${plan?.plan?.approvalRequired===false?"Not required":"Required before code changes"}</span></div></div>${priorities.length?`<div class="plan-priorities"><b>Plan priorities</b>${priorities.map(item=>`<div><strong>${escapeHtml(item.priority)} · ${escapeHtml(item.area)}</strong><span>${escapeHtml(item.reason)}</span></div>`).join("")}`:""}<div class="inspection-note">Read-only inspection · No code changes · No deployment</div>`;}
  function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;"," >":"&gt;",'"':"&quot;","'":"&#039;"}[c]||c));}
  renderWebsiteProjects();
})();
